### PR TITLE
bye bye C++ function: RecvStr

### PR DESCRIPTION
**Pull request by reqshark**
- this function was for receiving strings directly from nanomsg.
- RecvStr is redundant since we’re using streams.
- added `make full` command
- added circleci, easier said than done

### CODE REVIEW

**Comment by reqshark** [comment]
landed 5e722d1d69f3d05f682f89c2650295967a3b9006 haha

**Comment by marchon** [comment]
Is this all set?

**Comment by reqshark** [comment]
yes sir, we dont need it anymore since streams are taking all the buffers... that's their default

https://iojs.org/api/stream.html#stream_buffering

**Comment by reqshark** [comment]
oh maybe you were wondering about the commit code? 

i was playing around with `git rebase` and rewrote that history like how they do [on the iojs repo](https://github.com/iojs/io.js)

**Comment by marchon** [comment]
Oh got it now.

G.

On Sat, Feb 14, 2015 at 12:15 AM, Bent Cardan notifications@github.com
wrote:

> oh maybe you were wondering about the commit code?
> 
> i was playing around with git rebase and rewrote that history like how
> they do on the iojs repo https://github.com/iojs/io.js
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reqshark/nanomsg.iojs/pull/13#issuecomment-74362347.

## 

P THINK BEFORE PRINTING: is it really necessary?

This e-mail and its attachments are confidential and solely for the
intended addressee(s). Do not share or use them without approval. If
received in error, contact the sender
and delete them.

**Pull request closed without merging**
